lindell/multi-gitter

cmd/print.go, cmd/root.go, cmd/run.go, cmd/status.go, internal/multigitter/run.go, internal/multigitter/status.go, tests/story_test.go
this change does also include the renaming of some options to keep
concistency
=> feat!: added output option to differentiate log and other output

cmd/print.go, cmd/run.go, internal/git/git.go, internal/multigitter/print.go, internal/multigitter/run.go
=> feat: added --fetch-depth flag

.github/workflows/release.yaml, .goreleaser.yml, install.sh
and changes from binary release to tarballs
=> chore: added brew install

cmd/root.go, internal/scm/gitlab/gitlab.go
=> feat: added --include-subgroups flag

internal/multigitter/run.go
Slight fix to the interactive feature
Will help close issue #123
=> Slightly improve interface

cmd/cmd-run.go, go.mod, go.sum, internal/multigitter/run.go, internal/multigitter/terminal/terminal.go
Adds --interactive flag that allows the user to take manual decisions before committing any change.
Closes #167
=> Interactive mode 

internal/scm/gitlab/gitlab.go, internal/scm/gitlab/gitlab_test.go
=> fix: added support for GitLab subgroups with --project

cmd/cmd-status.go
=> feat: added --config to status command

cmd/logging.go, internal/log/censor-formatter.go, internal/log/censor-formatter_test.go, internal/log/default-censors.go
...even if the token is encoded (basic auth)
=> fix: censor http authentication header

cmd/cmd-run.go, tests/table_test.go
=> Multi line message fix

internal/multigitter/run.go, internal/scm/github/github.go, tests/table_test.go
=> fix: better logs when repositories are not used due to permissions

internal/multigitter/run.go, tests/table_test.go
=> fix: better error message when the same feature and base branch is used

internal/scm/github/pullrequest.go
=> fix(github): added missing closed pr status

cmd/cmd-run.go, internal/multigitter/run.go, internal/scm/gitea/gitea.go, internal/scm/github/github.go, internal/scm/gitlab/gitlab.go, internal/scm/pullrequest.go, tests/table_test.go
Closes #291 
Added label support for GitHub, GitLab and Gitea.
=> feat: added option to add labels to creates pull requests

internal/multigitter/merge.go
=> fix: allow individual merge failures without aborting all merges

cmd/platform.go
fix: input description for platform args
The param descriptions are currently incorrect or incomplete.
_Put any questions or notes for the reviewer here._
=> fix: input description for platform args

.github/ISSUE_TEMPLATE/feature_request.md
Adds a new issue template for feature requests.
=> docs: added feature request issue template

.github/workflows/release.yaml, .goreleaser.yml
=> ci: sign releases with gpg

internal/scm/github/github.go
=> fix(github): team reviewers no set without also setting reviewers

internal/scm/bitbucketcloud/bitbucket_cloud.go
=> fix: use http logger for BitBucket cloud
