cmd/root.go

Did I miss some flag or it's not possible to change baseurl for gitlab?
My usecase is to change it to gitlab url which we have as company self-managed

[gitlab] option to change base-url for gitlab

---

internal/scm/gitlab/gitlab.go

fix: made remove branch on merge the default behaviour for GitLab merge

---

cmd/root.go
internal/log/censor-formatter.go

fix: made sure any tokens output in the logs are now censored

---

internal/scm/github/github.go

fix(github): ignore branch deletion if branch is already deleted

---

cmd/platform.go

Ensure username is set so that bitbucket_server scm does not fail.
Validates that the `username` field is set for the `bitbucket_server` SCM type.

fix(bitbucket): ensure username is set

---

cmd/cmd-run.go
internal/git/cmdgit/git.go
internal/git/gogit/git.go
internal/multigitter/run.go
internal/multigitter/shared.go
internal/scm/bitbucketserver/bitbucket_server.go
internal/scm/gitea/gitea.go
internal/scm/github/github.go
internal/scm/gitlab/gitlab.go
tests/table_test.go
tests/vcmock/vcmock.go

This branchs adds `--conflict-strategy` and implements `skip` (previous default behaviour) and `replace`, where the changes to existing branches are replaced by a force push. The `append` strategy is intended to be implemented, but requires more additions and will be done separately. 
| Type | Description |
|-|-|
| Skip| The current behavior and the behavior that should most likely always be the default. Simply skip making any changes to the branch |
| ~Append~ | ~The changes are made on top of any already existing commits in the branch.~ |
| Replace | If a branch already exist and a change was made, replace it the new changes, and force push the changes. |
Closes #205

feat: added --conflict-strategy

---

cmd/platform.go
internal/scm/bitbucketserver/bitbucket_server.go
internal/scm/bitbucketserver/repository.go
internal/scm/gitea/gitea.go
internal/scm/gitea/repository.go
internal/scm/github/github.go
internal/scm/github/github_test.go
internal/scm/github/repository.go
internal/scm/gitlab/gitlab.go
internal/scm/gitlab/repository.go

feat: added --ssh-auth option

---

internal/scm/gitlab/gitlab.go

Changes the wrong behavior of deleting the Merge Request to closing the Merge Request.
Closes #229

fix(gitlab): close MR instead of deleting it

---

internal/scm/gitlab/gitlab.go
internal/scm/gitlab/repository.go

This PR sets the `Squash on merge` based on the project setting.
No issue has been created. I can do that if desired.
In my case I want to make some altercations after creating the Multi-Gitter MRs, but I almost always squash Merge Requests for a clean history on the main branch.

feat(gitlab): respect project level squash setting

---

cmd/cmd-run.go
internal/multigitter/run.go
internal/scm/gitea/gitea.go
internal/scm/github/github.go
internal/scm/gitlab/gitlab.go
internal/scm/pullrequest.go
tests/table_test.go

Adds ability to create Pull request as draft for GitHub, GitLab and Gitea.
Config:
Result:
Closes #225 
Had a question in #225 about modifying pull requests with draft status, but I think those can be addressed in a separate issue and MR.
Are you able to test this on GitHub? I'm not able to now, since my Multi-Gitter is setup for GitLab.
Also is there a way to write tests for this?

feat: add ability to create PR as draft

---

examples/general/clone.sh
internal/scm/gitlab/repository.go

This commit adds clone.sh, which clones the repositories down and copies them to a local folder while maintaining their org/user/group structure via folders.
It also fixes a possible bug as part of the gitlab api - the project.Namespace.Path value only contains the lowest subgroup, where the FullPath gets the entire group structure. 
Discussion #234 
Can you consider the implications of changing project.Namespace.Path to .FullPath? Will this cause any known issues?

Add Clone script

---

internal/scm/gitlab/gitlab.go

Skip `archived` projects when retrieving repositories for group/user projects on GitLab.
If a repository is archived on GitLab it is read-only. Therefor no changes can be made to the repository. 
Currently `multi-gitter` will still clone the repository and (try to) make changes for it. 
With the GitHub SCM archived repositories were already skipped. This PR also adds this behavior for GitLab.
N/A

feat(gitlab): skip archived repos

---

cmd/cmd-close.go
cmd/cmd-merge.go
cmd/cmd-print.go
cmd/cmd-run.go
cmd/cmd-status.go
cmd/platform.go
internal/scm/github/github.go
internal/scm/github/github_test.go

Without configuring platform run options. Not all repos are downloaded due to conditions.
Instead of:
DEBU[0000] Skipping repository since the token does not have push permissions and the run will not fork  repo=jenkinsci/opslevel-plugin
INFO[0000] Running on 0 repositories
You get:
INFO[0000] Running on 1 repositories
INFO[0000] Cloning and running script                    repo=jenkinsci/opslevel-plugin
Since jenkinsci/opslevel-plugin is a fork I have no push permissions and g.Fork always being false because `configureRunPlatform` is never run.
_Put any questions or notes for the reviewer here._

fix(github): allow only pull permission for print command

---

internal/scm/github/github.go
internal/scm/github/graphql.go
internal/scm/github/pullrequest.go

Once a change was partially merged, no further merge operations were possible as mutli-gitter tried to merge already merged PRs and GitHub returned.
`PUT https://api.github.com/repos/XYZ/pulls/40/merge: 405 Pull Request is not mergeable []`
Instead of returning all PRs for a branch, return only open PRs as there is currently no way to interact with already closed PRs.

fix: return open PRs only

---

internal/git/gogit/git.go
tests/scripts/remover/main.go
tests/table_test.go

Implements workaround where go-git would not add deleted files to the commit. It can hopefully be removed in the future. 
Closes #266

fix: deleted files are now detected with `git-type: go`

---

internal/scm/github/github.go
internal/scm/github/retry.go
internal/scm/github/retry_test.go

Adding retry mechanism to GitHub when doing changing API requests
Closes #276

fix: retry when encounting the GitHub rate limit

---

internal/scm/github/repository.go

This makes it possible to use new (still in beta) fine-grained access tokens for cloning and pushing.

fix(github): use other format when cloning with token to support more token formats

---

CONTRIBUTING.md
cmd/logging.go
internal/log/censor-formatter.go
internal/log/censor-formatter_test.go
internal/multigitter/repocounter/counter.go
internal/scm/github/github.go
tests/story_test.go

Fixes some typos in documentation, code, and comments.

fix: typos in docs and code

---

.github/workflows/test-install.yaml
install.sh

There are multiple fixes have been done to fix Windows installation:
1. `$OS` was comparing to _"windows"_ with first letter in lowercase, but it should be in uppercase
2. Removed `sudo install ...` line as it was a problem line for Windows.
3. Removed `adjust_format` function and its calling.
Closes #306
For the changes above:
**(2)** I ran it on macOS, Linux & Windows and everything passed successfully. Though, I feel that it might have impact on some users' environments, so it's up to the repo owner should `sudo` be back and another approach found or not.
**(3)** This one just doesn't make sense as all artifacts have `.tar.gz` format.
Also, I have added `.github/workflows/test-install.sh` pipeline to be sure that it is not broken in a future.
For future improvements:
1. Should line 54 …

Fix installation on Windows

---

cmd/platform.go
internal/scm/github/github.go

More information at #224 
The GitHub API does not return correct permission information when using app tokens. So don't use permissions to check if a repository should be included if that type of token is used.
Closes: #224

fix(github): allow GitHub app tokens to be used

---

cmd/platform.go
internal/scm/gitea/gitea.go
internal/scm/gitea/repository.go
internal/scm/github/github.go
internal/scm/github/github_test.go
internal/scm/gitlab/gitlab.go

Add support for filtering out repositories that are forks using `--skip-forks`.
See https://github.com/lindell/multi-gitter/discussions/340.
None.

feat: filter repositories that are forks

---

internal/multigitter/cmd.go
internal/multigitter/print.go
internal/multigitter/run.go

As discussed in PR #337 , this is the refactoring to consolidate the code for preparing command execution.
n/a
None.
- [/] Made sure the PR follows the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines
- [/] Tests if something new is added

refactor redundant code into a function

---

README.md
cmd/cmd-run.go
internal/multigitter/run.go
internal/scm/github/github.go
internal/scm/pullrequest.go
tests/table_test.go

_Give a summary of the change, and how it affects end-users. It's okay to copy/paste your commit messages._
Added support to assign github teams to pull requests using team `slug` (passed to the GH API).
```
go run main.go run $SCRIPT --config $CONFIG --token "$TOKEN"
INFO[0000] Running on 1 repositories                    
INFO[0000] Cloning and running script                    repo=marshmallow-insurance/{REPO}
INFO[0004] Pushing changes to remote                     repo=marshmallow-insurance/{REPO}
INFO[0005] Creating pull request                         repo=marshmallow-insurance/{REPO}
Repositories with a successful run:
marshmallow-insurance/{REPO} #9
```
`$CONFIG` file here contains flag `team-reviewers` and `max-team-reviewers` and other repo related configs.
Closes …

GitHub team review

---

.github/workflows/build.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/coverage.yaml
.github/workflows/docs.yaml
.github/workflows/linting.yaml
.github/workflows/readme.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml

Node 12 is deprecated. Use only actions using node 16

ci: updated github actions versions

---

internal/multigitter/print.go
internal/multigitter/repocounter/counter.go
internal/multigitter/run.go
tests/table_test.go

Currently if run is executed and the conflict strategy skip is set it correctly bypasses the branch push.
However it does not make sure a pull request exists.
I frequently run into the issue that I get rate limited by github because I run scripts against 200+ repositories. 
And if multi-gitter gets aborted at some point by me or because I shutdown my machine I am left with all branches pushed and not all pull requests opened. (Getting rate limited can lead to a loooong execution time of multi-gitter, not much we can do about it).
What I would need to fix this is to use the conflict strategy replace but I might not want that since I changed manually some branches already. Hence there is currently no option to ensure the pull requests actually exists.
This fix just makes sure that a pull …

fix: ensure pull request exists during conflict resolution

---

internal/multigitter/repocounter/counter.go
internal/multigitter/run.go

Inspired by @raffis change in #369. A small refactor of the repo counter to not have both a repository and a pull request list.

refactor: combined repositories and pull requests in repocounter

---

cmd/logging.go
internal/multigitter/repocounter/counter.go
internal/multigitter/status.go
internal/multigitter/terminal/terminal.go
tests/table_test.go
tests/vcmock/vcmock.go

Added the `--plain-output` option that ensures that output is not printed with terminal output and can be viewed as plain text.
Closes #314

feat: added --plain-output flag

---

cmd/platform.go
internal/scm/github/github.go
internal/scm/github/github_test.go

Using the `--repo-search` option, it is possible to supply a GitHub **repository** search query that is used to generate the set of repositories to process.
This feature is GItHub-only at the moment.
This allows for searches that reference:
- partial names with boolean queries: `owner:buildkite-plugins in:name docker AND plugin`
- one or multiple owners `owner:cultureamp owner:jamestelfer fork:true in:name plugin`
- README contents
- license
I initially started this as a "warm up" to implementing something similar with code search, but the partial name search and license search are potentially quite useful in themselves.
Obviously this means that search syntax and results depend on the underlying source being queried, so implementations for GitLab et al would be required to see this …

feat: use repo search to select repositories

---

.github/workflows/codeql-analysis.yml

Adds the `actions/setup-go` action to the CodeQL workflow so it has access to the correct version Go when running the analysis.

ci: add setup-go to CodeQL workflow

---

renovate.json

Turns on the Renovate [dependency dashboard](https://docs.renovatebot.com/configuration-options/#dependencydashboard) to make it easier to see what updates could be made. Also, it adds the JSON schema for the Renovate config format.

ci: turn on renovate dependency dashboard

---

.github/workflows/coverage.yaml
.github/workflows/release.yaml

Reduces permissions for the Github Actions in the two workflows that had yet to get explicit permissions set.
I'm not entirely sure what permissions Coveralls require, it seems they have not documented it. So, we can see if it runs fine with the given permissions or not. _Update: It was successful and uploaded the coverage._ 👍 
For the release workflow, I think the permissions are enough. But it was not completely documented for the commenter action. From what I can see in the [source code](https://github.com/apexskier/github-release-commenter), the Github calls are: lists releases (`contents: read`), compare commits (`contents: read`), comments and labels on linked issues/prs (`issues: write` and `pull-requests: write`), there's also a graphql query that I think should fly with the other …

ci: reduce Github Action permissions

---

renovate.json

Migrates the Renovate config to the current standard. I used the [`renovate-config-validator`](https://docs.renovatebot.com/config-validation/) command provided with `renovate@37` for the migration.

ci: migrate renovate config

---

renovate.json

This PR was based on the branch in https://github.com/lindell/multi-gitter/pull/417, so it has been rebased after that PR had been merged.
Adds Renovate config for maintaining Github Actions versions. It groups non-major Github Actions releases and update them monthly, while major releases require an approval on the Dependency Dashboard.
The package rules for Go modules are refined to specify that they are only for the `"gomod"` manager. And descriptions are added as well, to get a human readable description.

ci: renovate should maintain github actions

---

docs/README.template.md

Adds the OpenSSF scorecard badge of the repo to the readme.

docs: add OpenSSF scorecard badge to readme

---

.github/workflows/fuzz.yaml
cmd/cmd-run.go
tests/fuzzing_test.go

Adds a basic fuzzing test, a workflow to run it for 2 minutes, and a fix (max-revivers being negative will panic).

test: added fuzzing

---

internal/git/cmdgit/git.go
tests/table_test.go

Makes `BranchExist` in `cmdgit` match the full branch name. Previously, it would incorrectly return `true` if an existing branch started with the same name as the configured branch in `multi-gitter`. 
Added the test prior to implementing the fix and without the fix the test failed (as expected) when running with `--git-type cmd`.

fix: cmdgit BranchExist should match full branch name

---

cmd/cmd-run.go
internal/multigitter/run.go
tests/table_test.go

- Add --push-only flag to only push a feature branch
This feature adds a flag named --push-only to the run command which will allow developers to create feature branches without creating PRs.
Closes #454 
_Put any questions or notes for the reviewer here._

Feature #454 - Add --push-only flag to allow developers to only push the feature branch

---

internal/scm/github/github.go

When an existing PR exists and the `--draft` flag is not present in the run command, update the existing PR from "Draft" to "Ready For Review"
Closes #455.
I noticed this issue, and figured I would want to use it in some upcoming work I want to do. And I figured this is the one line change that you mentioned in https://github.com/lindell/multi-gitter/issues/455#issuecomment-1943135570. I saw that this already exists for the [Gitea](https://github.com/KasonBraley/multi-gitter/blob/7c252760299448dade4ce1cf226f76adac51e931/internal/scm/gitea/gitea.go#L353-L355) and [GitLab](https://github.com/KasonBraley/multi-gitter/blob/7c252760299448dade4ce1cf226f76adac51e931/internal/scm/gitlab/gitlab.go#L320-L322) implementations.  Let me know if there are any tests or anything else specific you'd like …

feat(github): Update existing draft PR to Ready For Review

---

internal/multigitter/run.go

The intractive usage says:
```
var interactiveInfo = `(V)iew changes. (A)ccept or (R)eject`
```
I was confused about it, and actually tried to press Shift+V.
Let's accept both lower and upprt case keys.

Accept capital chars in run command

---

.goreleaser.yml

- **chore(goreleaser): set `version: 2`**
- **chore(goreleaser): replace brews.foloder with brews.directory**
_Give a summary of the change, and how it affects end-users. It's okay to copy/paste your commit messages._
_For example if it introduces a new flag or modifies a commands output, give an example of you running the command and showing real output here._
Fixed GoReleaser config's errors.
https://github.com/lindell/multi-gitter/actions/runs/9755716855/job/26924701362
```
• only configurations files on version: 2 are supported, yours is version: 0, please update your configuration
⨯ release failed after 0s                  error=only configurations files on version: 2 are supported, yours is version: 0, please update your configuration
Error: The process …
```

chore: fix goreleaser config

---

internal/scm/bitbucketcloud/bitbucket_cloud.go

Instead of just getting the repository's default reviewers when creating a PR, also pull in the project inherited reviewers as well, to create the comprehensive list of reviewers. This is the default behavior that occurs when a user creates a PR in the Bitbucket Cloud UI. See documentation here https://developer.atlassian.com/cloud/bitbucket/rest/api-group-pullrequests/#api-repositories-workspace-repo-slug-effective-default-reviewers-get
This change is needed due to current behavior of BBC multi-gitter create PR is it will fail to include reviewers in the PR that are part of the project level default reviewer, but not explicitly repo level reviewer.

Include project level default reviewers for Bitbucket Cloud Create PR operation

---

cmd/cmd-print.go
cmd/cmd-run.go
docs/README.template.md

Minor grammar improvements to project documentation.
N/A
N/A

Minor improvements to documentation.

---

cmd/other.go
cmd/platform.go
docs/README.template.md
internal/scm/bitbucketcloud/bitbucket_cloud.go

Adds support for workspace token authentication in Bitbucket Cloud.
This change is needed because it provides more flexibility for authentication type (currently Bitbucket Cloud only supports app password authentication), and workspace token authentication is generally more secure.

add support for bitbucket workspace token authentication

---

cmd/cmd-print.go
cmd/cmd-run.go
internal/multigitter/run.go
main.go

These prints should have always been to stderr.
It opens up #441 to be implemented.

fix: print most things to stderr instead of stdout

---

internal/git/cmdgit/git.go

As discussed in #537, this adds the git standard output, and error streams in the trace log level, in order to troubleshoot git push failures (or other kind of git failures, that would be missed as not having this in trace level).
Closes #537 
* I'm also including the git "cmd line", so it's clear what the output belongs to
* _You'd mostly know that, as the output will be very familiar, but it makes sense to me to clarify this, if we're going to clarify this_
* As we're logging 3 distinct things (the cmd line, stdout, and stderr), I thought it would make sense to add that via structured logging that's available (the `withFields`), to make the log more readable, and possible to filter more easily there, if needed.
-  _I haven't added any additional tests, as this is a very small …

feat: Log stdout/err of cmdgit executions as Trace level

---

cmd/cmd-run.go
internal/git/changes.go
internal/git/gogit/git.go
internal/multigitter/run.go
internal/scm/changes.go
internal/scm/github/commit.go
internal/scm/github/graphql.go
internal/scm/github/repository.go
tests/table_test.go
tests/vcmock/vcmock.go

Based on #492
Push changes through the API instead of git. Only supported for GitHub.
It has the benefit of automatically producing verified commits. However, it is slower and not suited for changes to large files.

feat: add api-push

---

internal/scm/bitbucketserver/bitbucket_server.go

Switches delete to use a bearer token as the API expects in this case
_For example if it introduces a new flag or modifies a commands output, give an example of you running the command and showing real output here._
Closes #482
_If there is not an existing issue, please make sure we have context on why this change is needed. ._
_Put any questions or notes for the reviewer here._

adding bearer token fix for deleting a branch from bitbucket server

---

cmd/other.go
cmd/platform.go
go.mod
go.sum
internal/git/cmdgit/git.go
internal/git/gogit/git.go
internal/multigitter/run.go
internal/multigitter/shared.go
internal/scm/gerrit/change.go
internal/scm/gerrit/gerrit.go
internal/scm/gerrit/gerrit_test.go
internal/scm/gerrit/gogerrit_client.go
internal/scm/gerrit/repository.go
tests/repo_helper_test.go
tests/table_test.go
tests/vcmock/gerritmock.go

This pull request adds support for Gerrit as a version control system.
It implements the core logic for creating Gerrit reviews, merging/closing them, and searching for existing changes.
Future enhancements could include support for reviewers, team reviewers, assignees, draft, and label configurations.
Related to the discussion: https://github.com/lindell/multi-gitter/discussions/549
As discussed above, some logic in `run.go` was adjusted to accommodate Gerrit's workflow:
- Before pushing a commit, the commit message is enhanced with footers such as the Gerrit `Change-Id`.
- To check if a feature branch exists, the `VersionController` implementation is queried instead of the `SourceController` (since Gerrit does not use branches to track changes).
- With Gerrit, commits must be pushed to …

Implement Gerrit SCM
